/*
 * File:           C:\Users\mobleys\Documents\Analog Devices\SigmaStudio 3.10\Projects\ioti_DSP\AudioTests\Export\AudioTests_IC_1_PARAM.h
 *
 * Created:        Saturday, February 08, 2014 8:43:45 AM
 * Description:    AudioTests:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2014 Analog Devices, Inc. All rights reserved.
 */
#ifndef __AUDIOTESTS_IC_1_PARAM_H__
#define __AUDIOTESTS_IC_1_PARAM_H__


/* Module Modulo Size - Modulo Size*/
#define MOD_MODULOSIZE_COUNT                           1
#define MOD_MODULOSIZE_DEVICE                          "IC1"
#define MOD_MODULOSIZE_MODULO_SIZE_ADDR                0
#define MOD_MODULOSIZE_MODULO_SIZE_FIXPT               0x00002000
#define MOD_MODULOSIZE_MODULO_SIZE_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(8192)
#define MOD_MODULOSIZE_MODULO_SIZE_TYPE                SIGMASTUDIOTYPE_INTEGER

/* Module DC1 - DC Input Entry*/
#define MOD_DC1_COUNT                                  1
#define MOD_DC1_DEVICE                                 "IC1"
#define MOD_DC1_DCINPALG1_ADDR                         8
#define MOD_DC1_DCINPALG1_FIXPT                        0x005A7EF9
#define MOD_DC1_DCINPALG1_VALUE                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.707)
#define MOD_DC1_DCINPALG1_TYPE                         SIGMASTUDIOTYPE_FIXPOINT

/* Module Tone1 - Sine Tone*/
#define MOD_TONE1_COUNT                                5
#define MOD_TONE1_DEVICE                               "IC1"
#define MOD_TONE1_ALG0_INCREMENT_ADDR                  9
#define MOD_TONE1_ALG0_INCREMENT_FIXPT                 0x00012C5F
#define MOD_TONE1_ALG0_INCREMENT_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00916666666666667)
#define MOD_TONE1_ALG0_INCREMENT_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_STATIC_TONE1_ALG0_MASK_ADDR                10
#define MOD_STATIC_TONE1_ALG0_MASK_FIXPT               0x000000FF
#define MOD_STATIC_TONE1_ALG0_MASK_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_TONE1_ALG0_MASK_TYPE                SIGMASTUDIOTYPE_INTEGER
#define MOD_TONE1_ALG0_ON_ADDR                         11
#define MOD_TONE1_ALG0_ON_FIXPT                        0x00800000
#define MOD_TONE1_ALG0_ON_VALUE                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_TONE1_ALG0_ON_TYPE                         SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TONE1_ALG0_DATA_ADR_ADDR                   12
#define MOD_TONE1_ALG0_DATA_ADR_FIXPT                  0x00000002
#define MOD_TONE1_ALG0_DATA_ADR_VALUE                  SIGMASTUDIOTYPE_INTEGER_CONVERT(2)
#define MOD_TONE1_ALG0_DATA_ADR_TYPE                   SIGMASTUDIOTYPE_INTEGER
#define MOD_TONE1_ALG0_COEFF_ADR_ADDR                  13
#define MOD_TONE1_ALG0_COEFF_ADR_FIXPT                 0x00000009
#define MOD_TONE1_ALG0_COEFF_ADR_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(9)
#define MOD_TONE1_ALG0_COEFF_ADR_TYPE                  SIGMASTUDIOTYPE_INTEGER

/* Module W Noise1 - White Noise*/
#define MOD_WNOISE1_COUNT                              3
#define MOD_WNOISE1_DEVICE                             "IC1"
#define MOD_WNOISE1_ALG0_ENABLENOISE_ADDR              14
#define MOD_WNOISE1_ALG0_ENABLENOISE_FIXPT             0x00800000
#define MOD_WNOISE1_ALG0_ENABLENOISE_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_WNOISE1_ALG0_ENABLENOISE_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_WNOISE1_ALG0_SEED_ADDR                     15
#define MOD_WNOISE1_ALG0_SEED_FIXPT                    0x0005464B
#define MOD_WNOISE1_ALG0_SEED_VALUE                    SIGMASTUDIOTYPE_INTEGER_CONVERT(345675)
#define MOD_WNOISE1_ALG0_SEED_TYPE                     SIGMASTUDIOTYPE_INTEGER
#define MOD_WNOISE1_ALG0_SEED_ADDR                     15
#define MOD_WNOISE1_ALG0_SEED_FIXPT                    0x0005464B
#define MOD_WNOISE1_ALG0_SEED_VALUE                    SIGMASTUDIOTYPE_INTEGER_CONVERT(345675)
#define MOD_WNOISE1_ALG0_SEED_TYPE                     SIGMASTUDIOTYPE_INTEGER

/* Module Square1 - Square wave*/
#define MOD_SQUARE1_COUNT                              3
#define MOD_SQUARE1_DEVICE                             "IC1"
#define MOD_STATIC_SQUARE1_ALG0_MASK_ADDR              16
#define MOD_STATIC_SQUARE1_ALG0_MASK_FIXPT             0x000000FF
#define MOD_STATIC_SQUARE1_ALG0_MASK_VALUE             SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_SQUARE1_ALG0_MASK_TYPE              SIGMASTUDIOTYPE_INTEGER
#define MOD_SQUARE1_ALG0_FREQ_ADDR                     17
#define MOD_SQUARE1_ALG0_FREQ_FIXPT                    0x00012C5F
#define MOD_SQUARE1_ALG0_FREQ_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00916666666666667)
#define MOD_SQUARE1_ALG0_FREQ_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SQUARE1_ALG0_ON_ADDR                       18
#define MOD_SQUARE1_ALG0_ON_FIXPT                      0x00800000
#define MOD_SQUARE1_ALG0_ON_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SQUARE1_ALG0_ON_TYPE                       SIGMASTUDIOTYPE_FIXPOINT

/* Module Nx1-1 - Mono Switch Nx1*/
#define MOD_NX1_1_COUNT                                4
#define MOD_NX1_1_DEVICE                               "IC1"
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR    19
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT   0x00000000
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR    20
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT   0x00800000
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_NX1_1_ALG0_STAGE2_MONOSWITCHNOSLEW_ADDR    21
#define MOD_NX1_1_ALG0_STAGE2_MONOSWITCHNOSLEW_FIXPT   0x00000000
#define MOD_NX1_1_ALG0_STAGE2_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_NX1_1_ALG0_STAGE2_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_NX1_1_ALG0_STAGE3_MONOSWITCHNOSLEW_ADDR    22
#define MOD_NX1_1_ALG0_STAGE3_MONOSWITCHNOSLEW_FIXPT   0x00000000
#define MOD_NX1_1_ALG0_STAGE3_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_NX1_1_ALG0_STAGE3_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module Level1 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL1_COUNT                               3
#define MOD_LEVEL1_DEVICE                              "IC1"
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_ADDR 23
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_FIXPT 0x00002752
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00119998247277842)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_ADDR 24
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_FIXPT 0x000003C0
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(960)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_ADDR 25
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_FIXPT 0x0000038E
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000108506944444444)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Single 1 - Single Volume*/
#define MOD_SINGLE1_COUNT                              1
#define MOD_SINGLE1_DEVICE                             "IC1"
#define MOD_SINGLE1_GAIN1940ALGNS1_ADDR                30
#define MOD_SINGLE1_GAIN1940ALGNS1_FIXPT               0x0050C335
#define MOD_SINGLE1_GAIN1940ALGNS1_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.630957344480193)
#define MOD_SINGLE1_GAIN1940ALGNS1_TYPE                SIGMASTUDIOTYPE_FIXPOINT

/* Module M Splitter2 - Multiple Control Splitter*/
#define MOD_MSPLITTER2_COUNT                           2
#define MOD_MSPLITTER2_DEVICE                          "IC1"
#define MOD_MSPLITTER2_ALG0_STAGE0_MULTICTRLSPLITTER31_ADDR 31
#define MOD_MSPLITTER2_ALG0_STAGE0_MULTICTRLSPLITTER31_FIXPT 0x00800000
#define MOD_MSPLITTER2_ALG0_STAGE0_MULTICTRLSPLITTER31_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER2_ALG0_STAGE0_MULTICTRLSPLITTER31_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER2_ALG0_STAGE1_MULTICTRLSPLITTER32_ADDR 32
#define MOD_MSPLITTER2_ALG0_STAGE1_MULTICTRLSPLITTER32_FIXPT 0x00800000
#define MOD_MSPLITTER2_ALG0_STAGE1_MULTICTRLSPLITTER32_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER2_ALG0_STAGE1_MULTICTRLSPLITTER32_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module M Splitter1 - Multiple Control Splitter*/
#define MOD_MSPLITTER1_COUNT                           8
#define MOD_MSPLITTER1_DEVICE                          "IC1"
#define MOD_MSPLITTER1_ALG0_STAGE0_MULTICTRLSPLITTER11_ADDR 33
#define MOD_MSPLITTER1_ALG0_STAGE0_MULTICTRLSPLITTER11_FIXPT 0x00800000
#define MOD_MSPLITTER1_ALG0_STAGE0_MULTICTRLSPLITTER11_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_ALG0_STAGE0_MULTICTRLSPLITTER11_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_ALG0_STAGE1_MULTICTRLSPLITTER12_ADDR 34
#define MOD_MSPLITTER1_ALG0_STAGE1_MULTICTRLSPLITTER12_FIXPT 0x00721482
#define MOD_MSPLITTER1_ALG0_STAGE1_MULTICTRLSPLITTER12_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.891250938133746)
#define MOD_MSPLITTER1_ALG0_STAGE1_MULTICTRLSPLITTER12_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_ALG0_STAGE2_MULTICTRLSPLITTER13_ADDR 35
#define MOD_MSPLITTER1_ALG0_STAGE2_MULTICTRLSPLITTER13_FIXPT 0x00800000
#define MOD_MSPLITTER1_ALG0_STAGE2_MULTICTRLSPLITTER13_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_ALG0_STAGE2_MULTICTRLSPLITTER13_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_ALG0_STAGE3_MULTICTRLSPLITTER14_ADDR 36
#define MOD_MSPLITTER1_ALG0_STAGE3_MULTICTRLSPLITTER14_FIXPT 0x00800000
#define MOD_MSPLITTER1_ALG0_STAGE3_MULTICTRLSPLITTER14_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_ALG0_STAGE3_MULTICTRLSPLITTER14_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_ALG0_STAGE4_MULTICTRLSPLITTER15_ADDR 37
#define MOD_MSPLITTER1_ALG0_STAGE4_MULTICTRLSPLITTER15_FIXPT 0x00800000
#define MOD_MSPLITTER1_ALG0_STAGE4_MULTICTRLSPLITTER15_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_ALG0_STAGE4_MULTICTRLSPLITTER15_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_ALG0_STAGE5_MULTICTRLSPLITTER16_ADDR 38
#define MOD_MSPLITTER1_ALG0_STAGE5_MULTICTRLSPLITTER16_FIXPT 0x00800000
#define MOD_MSPLITTER1_ALG0_STAGE5_MULTICTRLSPLITTER16_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_ALG0_STAGE5_MULTICTRLSPLITTER16_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_ALG0_STAGE6_MULTICTRLSPLITTER17_ADDR 39
#define MOD_MSPLITTER1_ALG0_STAGE6_MULTICTRLSPLITTER17_FIXPT 0x00800000
#define MOD_MSPLITTER1_ALG0_STAGE6_MULTICTRLSPLITTER17_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_ALG0_STAGE6_MULTICTRLSPLITTER17_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_ALG0_STAGE7_MULTICTRLSPLITTER18_ADDR 40
#define MOD_MSPLITTER1_ALG0_STAGE7_MULTICTRLSPLITTER18_FIXPT 0x00800000
#define MOD_MSPLITTER1_ALG0_STAGE7_MULTICTRLSPLITTER18_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_ALG0_STAGE7_MULTICTRLSPLITTER18_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module M Splitter1_2 - Multiple Control Splitter*/
#define MOD_MSPLITTER1_2_COUNT                         8
#define MOD_MSPLITTER1_2_DEVICE                        "IC1"
#define MOD_MSPLITTER1_2_ALG0_STAGE0_MULTICTRLSPLITTER21_ADDR 41
#define MOD_MSPLITTER1_2_ALG0_STAGE0_MULTICTRLSPLITTER21_FIXPT 0x00800000
#define MOD_MSPLITTER1_2_ALG0_STAGE0_MULTICTRLSPLITTER21_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_2_ALG0_STAGE0_MULTICTRLSPLITTER21_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_2_ALG0_STAGE1_MULTICTRLSPLITTER22_ADDR 42
#define MOD_MSPLITTER1_2_ALG0_STAGE1_MULTICTRLSPLITTER22_FIXPT 0x00800000
#define MOD_MSPLITTER1_2_ALG0_STAGE1_MULTICTRLSPLITTER22_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_2_ALG0_STAGE1_MULTICTRLSPLITTER22_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_2_ALG0_STAGE2_MULTICTRLSPLITTER23_ADDR 43
#define MOD_MSPLITTER1_2_ALG0_STAGE2_MULTICTRLSPLITTER23_FIXPT 0x00800000
#define MOD_MSPLITTER1_2_ALG0_STAGE2_MULTICTRLSPLITTER23_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_2_ALG0_STAGE2_MULTICTRLSPLITTER23_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_2_ALG0_STAGE3_MULTICTRLSPLITTER24_ADDR 44
#define MOD_MSPLITTER1_2_ALG0_STAGE3_MULTICTRLSPLITTER24_FIXPT 0x00800000
#define MOD_MSPLITTER1_2_ALG0_STAGE3_MULTICTRLSPLITTER24_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_2_ALG0_STAGE3_MULTICTRLSPLITTER24_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_2_ALG0_STAGE4_MULTICTRLSPLITTER25_ADDR 45
#define MOD_MSPLITTER1_2_ALG0_STAGE4_MULTICTRLSPLITTER25_FIXPT 0x00800000
#define MOD_MSPLITTER1_2_ALG0_STAGE4_MULTICTRLSPLITTER25_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_2_ALG0_STAGE4_MULTICTRLSPLITTER25_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_2_ALG0_STAGE5_MULTICTRLSPLITTER26_ADDR 46
#define MOD_MSPLITTER1_2_ALG0_STAGE5_MULTICTRLSPLITTER26_FIXPT 0x00800000
#define MOD_MSPLITTER1_2_ALG0_STAGE5_MULTICTRLSPLITTER26_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_2_ALG0_STAGE5_MULTICTRLSPLITTER26_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_2_ALG0_STAGE6_MULTICTRLSPLITTER27_ADDR 47
#define MOD_MSPLITTER1_2_ALG0_STAGE6_MULTICTRLSPLITTER27_FIXPT 0x00800000
#define MOD_MSPLITTER1_2_ALG0_STAGE6_MULTICTRLSPLITTER27_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_2_ALG0_STAGE6_MULTICTRLSPLITTER27_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MSPLITTER1_2_ALG0_STAGE7_MULTICTRLSPLITTER28_ADDR 48
#define MOD_MSPLITTER1_2_ALG0_STAGE7_MULTICTRLSPLITTER28_FIXPT 0x00800000
#define MOD_MSPLITTER1_2_ALG0_STAGE7_MULTICTRLSPLITTER28_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MSPLITTER1_2_ALG0_STAGE7_MULTICTRLSPLITTER28_TYPE SIGMASTUDIOTYPE_FIXPOINT

#endif
