/*
 * File:           C:\Users\mobleys\Documents\Analog Devices\SigmaStudio 3.10\Projects\ioti_DSP\PassThru96K\export\pass-thru-96K_ADAU1445_PARAM.h
 *
 * Created:        Saturday, April 05, 2014 11:34:43 AM
 * Description:    pass-thru-96K:ADAU1445 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2014 Analog Devices, Inc. All rights reserved.
 */
#ifndef __PASS_THRU_96K_ADAU1445_PARAM_H__
#define __PASS_THRU_96K_ADAU1445_PARAM_H__


/* Module Modulo Size - Modulo Size*/
#define MOD_MODULOSIZE_COUNT                           1
#define MOD_MODULOSIZE_DEVICE                          "ADAU1445"
#define MOD_MODULOSIZE_MODULO_SIZE_ADDR                0
#define MOD_MODULOSIZE_MODULO_SIZE_FIXPT               0x00002000
#define MOD_MODULOSIZE_MODULO_SIZE_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(8192)
#define MOD_MODULOSIZE_MODULO_SIZE_TYPE                SIGMASTUDIOTYPE_INTEGER

/* Module DCB2 - DC Blocking*/
#define MOD_DCB2_COUNT                                 1
#define MOD_DCB2_DEVICE                                "ADAU1445"
#define MOD_DCB2_DCBLOCKALGDOUBLEPREC2POLE_ADDR        8
#define MOD_DCB2_DCBLOCKALGDOUBLEPREC2POLE_FIXPT       0x007FFCB9
#define MOD_DCB2_DCBLOCKALGDOUBLEPREC2POLE_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DCB2_DCBLOCKALGDOUBLEPREC2POLE_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB3 - DC Blocking*/
#define MOD_DCB3_COUNT                                 1
#define MOD_DCB3_DEVICE                                "ADAU1445"
#define MOD_DCB3_DCBLOCKALGDOUBLEPREC3POLE_ADDR        9
#define MOD_DCB3_DCBLOCKALGDOUBLEPREC3POLE_FIXPT       0x007FFCB9
#define MOD_DCB3_DCBLOCKALGDOUBLEPREC3POLE_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DCB3_DCBLOCKALGDOUBLEPREC3POLE_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB5 - DC Blocking*/
#define MOD_DCB5_COUNT                                 1
#define MOD_DCB5_DEVICE                                "ADAU1445"
#define MOD_DCB5_DCBLOCKALGDOUBLEPREC5POLE_ADDR        10
#define MOD_DCB5_DCBLOCKALGDOUBLEPREC5POLE_FIXPT       0x007FFCB9
#define MOD_DCB5_DCBLOCKALGDOUBLEPREC5POLE_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DCB5_DCBLOCKALGDOUBLEPREC5POLE_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB6 - DC Blocking*/
#define MOD_DCB6_COUNT                                 1
#define MOD_DCB6_DEVICE                                "ADAU1445"
#define MOD_DCB6_DCBLOCKALGDOUBLEPREC6POLE_ADDR        11
#define MOD_DCB6_DCBLOCKALGDOUBLEPREC6POLE_FIXPT       0x007FFCB9
#define MOD_DCB6_DCBLOCKALGDOUBLEPREC6POLE_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DCB6_DCBLOCKALGDOUBLEPREC6POLE_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB7 - DC Blocking*/
#define MOD_DCB7_COUNT                                 1
#define MOD_DCB7_DEVICE                                "ADAU1445"
#define MOD_DCB7_DCBLOCKALGDOUBLEPREC7POLE_ADDR        12
#define MOD_DCB7_DCBLOCKALGDOUBLEPREC7POLE_FIXPT       0x007FFCB9
#define MOD_DCB7_DCBLOCKALGDOUBLEPREC7POLE_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DCB7_DCBLOCKALGDOUBLEPREC7POLE_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB8 - DC Blocking*/
#define MOD_DCB8_COUNT                                 1
#define MOD_DCB8_DEVICE                                "ADAU1445"
#define MOD_DCB8_DCBLOCKALGDOUBLEPREC8POLE_ADDR        13
#define MOD_DCB8_DCBLOCKALGDOUBLEPREC8POLE_FIXPT       0x007FFCB9
#define MOD_DCB8_DCBLOCKALGDOUBLEPREC8POLE_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DCB8_DCBLOCKALGDOUBLEPREC8POLE_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB1 - DC Blocking*/
#define MOD_DCB1_COUNT                                 1
#define MOD_DCB1_DEVICE                                "ADAU1445"
#define MOD_DCB1_DCBLOCKALGDOUBLEPREC1POLE_ADDR        14
#define MOD_DCB1_DCBLOCKALGDOUBLEPREC1POLE_FIXPT       0x007FFCB9
#define MOD_DCB1_DCBLOCKALGDOUBLEPREC1POLE_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DCB1_DCBLOCKALGDOUBLEPREC1POLE_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module DCB4 - DC Blocking*/
#define MOD_DCB4_COUNT                                 1
#define MOD_DCB4_DEVICE                                "ADAU1445"
#define MOD_DCB4_DCBLOCKALGDOUBLEPREC4POLE_ADDR        15
#define MOD_DCB4_DCBLOCKALGDOUBLEPREC4POLE_FIXPT       0x007FFCB9
#define MOD_DCB4_DCBLOCKALGDOUBLEPREC4POLE_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.9999)
#define MOD_DCB4_DCBLOCKALGDOUBLEPREC4POLE_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module Level1 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL1_COUNT                               3
#define MOD_LEVEL1_DEVICE                              "ADAU1445"
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_ADDR 16
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_FIXPT 0x00002752
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00119998247277842)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_ADDR 17
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_FIXPT 0x000003C0
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(960)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_ADDR 18
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_FIXPT 0x0000038E
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000108506944444444)
#define MOD_LEVEL1_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN1DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Level2 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL2_COUNT                               3
#define MOD_LEVEL2_DEVICE                              "ADAU1445"
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2TCONST_ADDR 23
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2TCONST_FIXPT 0x00002752
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00119998247277842)
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2HOLD_ADDR 24
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2HOLD_FIXPT 0x000003C0
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(960)
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2DECAY_ADDR 25
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2DECAY_FIXPT 0x0000038E
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000108506944444444)
#define MOD_LEVEL2_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN2DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Level3 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL3_COUNT                               3
#define MOD_LEVEL3_DEVICE                              "ADAU1445"
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3TCONST_ADDR 30
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3TCONST_FIXPT 0x00002752
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00119998247277842)
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3HOLD_ADDR 31
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3HOLD_FIXPT 0x000003C0
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(960)
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3DECAY_ADDR 32
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3DECAY_FIXPT 0x0000038E
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000108506944444444)
#define MOD_LEVEL3_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN3DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Level4 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL4_COUNT                               3
#define MOD_LEVEL4_DEVICE                              "ADAU1445"
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4TCONST_ADDR 37
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4TCONST_FIXPT 0x00002752
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00119998247277842)
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4HOLD_ADDR 38
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4HOLD_FIXPT 0x000003C0
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(960)
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4DECAY_ADDR 39
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4DECAY_FIXPT 0x0000038E
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000108506944444444)
#define MOD_LEVEL4_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN4DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Level5 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL5_COUNT                               3
#define MOD_LEVEL5_DEVICE                              "ADAU1445"
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5TCONST_ADDR 44
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5TCONST_FIXPT 0x00002752
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00119998247277842)
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5HOLD_ADDR 45
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5HOLD_FIXPT 0x000003C0
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(960)
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5DECAY_ADDR 46
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5DECAY_FIXPT 0x0000038E
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000108506944444444)
#define MOD_LEVEL5_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN5DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Level6 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL6_COUNT                               3
#define MOD_LEVEL6_DEVICE                              "ADAU1445"
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6TCONST_ADDR 51
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6TCONST_FIXPT 0x00002752
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00119998247277842)
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6HOLD_ADDR 52
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6HOLD_FIXPT 0x000003C0
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(960)
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6DECAY_ADDR 53
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6DECAY_FIXPT 0x0000038E
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000108506944444444)
#define MOD_LEVEL6_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN6DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Level7 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL7_COUNT                               3
#define MOD_LEVEL7_DEVICE                              "ADAU1445"
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7TCONST_ADDR 58
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7TCONST_FIXPT 0x00002752
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00119998247277842)
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7HOLD_ADDR 59
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7HOLD_FIXPT 0x000003C0
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(960)
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7DECAY_ADDR 60
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7DECAY_FIXPT 0x0000038E
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000108506944444444)
#define MOD_LEVEL7_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN7DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Level8 - Single Level Detector w Numerical Display*/
#define MOD_LEVEL8_COUNT                               3
#define MOD_LEVEL8_DEVICE                              "ADAU1445"
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8TCONST_ADDR 65
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8TCONST_FIXPT 0x00002752
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00119998247277842)
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8HOLD_ADDR 66
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8HOLD_FIXPT 0x000003C0
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(960)
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8DECAY_ADDR 67
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8DECAY_FIXPT 0x0000038E
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000108506944444444)
#define MOD_LEVEL8_ALG0_SINGLEBANDLEVELDETWOUTDISP3RDGEN8DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

#endif
